fix: Composition with sawtooth
btpworks/chronicle-examples pull request #48
Opened 2022-12-18 18:39 UTC by ryanbtp

* Fix devmode in validator
* Ensure correct version of tp is used

Signed-off-by: Ryan Roberts <ryan.roberts@btp.works>

2023-01-10 12:16 UTC, mtbc commented on README.md
> +This contains several example domain yaml files and docker and uses
It contains docker?

2023-01-10 12:19 UTC, mtbc commented on docker/chronicle-test/chronicle-test
> +echo "Wait for stack"
Could `set -e` be a safe/good option?

2023-01-10 15:04 UTC, ryanbtp commented on README.md
> +This contains several example domain yaml files and docker and uses
Oops

2023-01-12 15:03 UTC, mtbc commented
This seems to run fine on x86_64 GNU/Linux.

2023-02-06 15:17 UTC, suchapalaver commented on docker/chronicle.dockerfile
> +FROM ubuntu:focal AS domain-base
```suggestion
FROM ubuntu:jammy AS domain-base
```
That change got things working for me, working off this branch.

2023-02-06 15:18 UTC, suchapalaver commented on Makefile
> +	 $(COMPOSE) -f docker/chronicle.yaml up --exit-code-from chronicle-test
```suggestion
	 $(COMPOSE) -f docker/docker-compose.yaml up --exit-code-from chronicle-test
```

2023-02-07 14:10 UTC, suchapalaver commented
Running `make run-sawtooth-manufacturing`, I still get the following error:

```
export CHRONICLE_IMAGE=chronicle-manufacturing-sawtooth; export CHRONICLE_VERSION=local; docker-compose -f docker/chronicle.yaml up -d
ERROR: .FileNotFoundError: [Errno 2] No such file or directory: './docker/chronicle.yaml'
make: *** [Makefile:207: run-sawtooth-manufacturing] Error 1
```

2023-02-07 20:08 UTC, suchapalaver commented on Makefile
> +	docker-compose -f docker/cronicle.yaml down -v --rmi all || true
```suggestion
	docker-compose -f docker/chronicle.yaml down -v --rmi all || true
```

2023-02-08 17:26 UTC, suchapalaver commented
Trying this out, I've had things working successfully with the logs showing things working in the validator and the domain container, but I also keep running into the following error:

```
Pulling domain (chronicle-manufacturing-sawtooth:local)...
ERROR: The image for the service you're trying to recreate has been removed. If you continue, volume data could be lost. Consider backing up your data before continuing.

Continue with the new image? [yN]y
Pulling domain (chronicle-manufacturing-sawtooth:local)...
ERROR: pull access denied for chronicle-manufacturing-sawtooth, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
make: *** [Makefile:211: run-sawtooth-manufacturing] Error 1
```
Building everything again from scratch the `make run-sawtooth-manufacturing` process stops at the above error. That image does not exist for me, only the following:

```
$ docker images
REPOSITORY                                  TAG              IMAGE ID       CREATED         SIZE
blockchaintp/chronicle-tp-amd64             BTP2.1.0-0.6.0   b9a14875b161   6 days ago      101MB
postgres                                    13.9-alpine      8e750948d39a   4 weeks ago     238MB
blockchaintp/sawtooth-validator             BTP2.1.0         42a6dfdbfc22   7 weeks ago     749MB
blockchaintp/sawtooth-settings-tp           BTP2.1.0         0202fb5b0aaf   7 weeks ago     223MB
blockchaintp/sawtooth-rest-api              BTP2.1.0         e0e708a4b477   7 weeks ago     272MB
blockchaintp/sawtooth-devmode-engine-rust   BTP2.1.0         dbd8b60f760a   13 months ago   300MB
```

2023-02-08 18:03 UTC, mtbc commented on Makefile
> +	docker-compose -f docker/cronicle.yaml down -v --rmi all || true
Still seems to need fixed?

2023-02-09 14:00 UTC, scealiontach commented on Makefile
> +.PHONY: package
package analyze publish and test are all PHONYed and defined in standard_defs.mk

2023-02-09 14:29 UTC, ryanbtp commented on Makefile
> +		chronicle-$(1)-sawtooth:$(ISOLATION_ID)
The reason was me getting confused between stl and sdl. I'll change it back

2023-02-10 10:57 UTC, ryanbtp commented on docker/chronicle.dockerfile
> +ARG CHRONICLE_VERSION
Now has the architecture in the name of the image

2023-02-10 10:59 UTC, ryanbtp commented
Rebuild after cleaning containers without cleaning the markers should now work, with a small cost to build times

2023-02-10 11:36 UTC, mtbc commented
Out of curiosity I tried `make run-stl-artworld` and it started,
```
...
Makefile:183: warning: overriding recipe for target 'build-end-to-end-test'
Makefile:183: warning: ignoring old recipe for target 'build-end-to-end-test'
Makefile:183: warning: overriding recipe for target 'test-e2e'
Makefile:183: warning: ignoring old recipe for target 'test-e2e'
make: Circular artworld-stl <- artworld-stl dependency dropped.
...
```
(It looked fairly happy afterward.)

2023-02-15 10:45 UTC, mtbc commented
Build runs into,
> error: couldn't read crates/chronicle-domain/src/main.rs: No such file or directory

2023-02-20 10:22 UTC, ryanbtp commented
> Build runs into,
> 
> > error: couldn't read crates/chronicle-domain/src/main.rs: No such file or directory

Fixed, hopefully! CI test was using wrong entrypoint

2023-02-20 17:31 UTC, scealiontach requested changes

2023-02-20 17:31 UTC, scealiontach commented on docker/chronicle.dockerfile
> +ARG CHRONICLE_VERSION
Should still have a default here.  Put the default back in with the amd64 image or if you like make it smarter with TARGETARCH

2023-02-20 17:31 UTC, scealiontach commented on docker/chronicle.yaml
> +    entrypoint: >
Can we put the formatting back to the original here.  The `>` and `&&` version is both less readable and more error-prone, than the `-exc` and `|` version.

2023-02-20 17:31 UTC, scealiontach commented on docker/chronicle.yaml
> +      - -xc
if you make it  `-exc` you can lose the `&&`'s

2023-02-21 16:09 UTC, scealiontach approved these changes

2023-02-24 14:48 UTC, merged