fix(domains): remove evidence domain
btpworks/chronicle-examples pull request #60
Opened 2023-02-01 17:42 UTC by scealiontach

Evidence domain can be confusing wrt the evidence functionality in chronicle, which is still a wip

Signed-off-by: Kevin O'Donnell <kevin@blockchaintp.com>

2023-02-01 17:54 UTC, mtbc requested changes
Also remove from `README.md` and `mkdocs.yml`.

2023-02-01 17:56 UTC, ryanbtp commented
The documentation should probably be migrated to a new example too in this case

2023-02-01 17:56 UTC, ryanbtp approved these changes

2023-02-02 17:52 UTC, suchapalaver commented
Added changes requested by @mtbc, fixing them into Kevin's original commit, hence the change in authorship.

Signed-off-by: Joseph Livesey [joseph.livesey@btp.works](mailto:joseph.livesey@btp.works)

2023-02-02 17:52 UTC, mtbc approved these changes

2023-02-02 17:53 UTC, merged