chore: Update to .7
btpworks/chronicle-examples pull request #91
Opened 2023-06-06 13:20 UTC by ryan-s-roberts

* Use registry version BTP2.1.0-0.7.1
* Support the new version embedding by echoing from make
* Clean up .dockerignore to ignore all + allow
* Add log filters to calm down the wasm tracing

Ref: CHRON-381

Note this will not build until there is a published BTP2.1.0-0.7.1

# PR Checklist

## Please complete this checklist after opening your PR

* [x] I have updated documentation as necessary
* [x] I have updated helm chart(s) if needed
* [x] I have added tests if needed
* [ ] All new and existing tests are passing
* [x] Any breaking changes are clearly flagged and documented
* [x] I’ve included a link to any relevant ticket(s)

2023-06-07 08:21 UTC, mtbc commented on Makefile
> +
intended?

2023-06-07 21:26 UTC, scealiontach requested changes

2023-06-07 21:26 UTC, scealiontach commented on docker/chronicle.dockerfile
> +COPY .VERSION /app/.VERSION
this file doesn't exist, nor is it generated by the Makefile

2023-06-08 09:18 UTC, scealiontach requested changes

2023-06-08 09:18 UTC, scealiontach commented on docker/chronicle.dockerfile
> +ARG CHRONICLE_VERSION=BTP2.1.0-0.7.2
update this one to 0.7.3 as well

2023-06-08 10:02 UTC, scealiontach approved these changes

2023-06-08 10:42 UTC, mtbc commented on policies/common_rules.rego
> +
can omit the trailing blanks

2023-06-08 11:01 UTC, mtbc commented
`make run-stl-artworld` gives me an artworld that interacts fine via GraphQL.

2023-06-08 14:36 UTC, merged