adjust build targets and image naming
btpworks/chronicle-examples pull request #92
Opened 2023-06-07 08:56 UTC by mtbc

Following discussion on CHRON-373 about #90, this:

- saves time by not usually bothering with debug builds (except for `run-*` targets)
- emphasizes release builds (as we aren't doing incremental builds anyway)
- documents the targets rather better, especially for `all` vs `stl`
- deprecates image names not suffixed `-release` or `-debug`.

# PR Checklist

## Please complete this checklist after opening your PR

* [x] I have updated documentation as necessary
* [x] I have updated helm chart(s) if needed
* [x] I have added tests if needed
* [x] All new and existing tests are passing
* [x] Any breaking changes are clearly flagged and documented
* [x] I’ve included a link to any relevant ticket(s)

2023-06-19 16:20 UTC, scealiontach requested changes

2023-06-20 11:12 UTC, mtbc commented on Makefile
>  .PHONY: $(1)-stl
Hadn't noticed that issue, will fix those in this PR too.

2023-06-20 11:12 UTC, mtbc commented on Makefile
> +$(1)-inmem: $(1)-inmem-release
The idea is to prevent the debug images being built unless specifically requested. Will try a different approach.

2023-06-21 13:47 UTC, scealiontach approved these changes

2023-06-21 16:41 UTC, merged